#! /bin/bash

[ -v cc ] || cc=gcc
[ -v cxx ] || cxx=g++

#build machete
cd machete
mkdir -p lib obj bin
make 
cp lib/* ../lib/
cp mach ../bin/
cd .. 

#build SZ test
$cxx other/test_sz.cpp -o bin/sztest -Llib -lSZ 

#build Gorilla test
cd gorilla
go build 
cp gorilla ../bin/gorilla 
cd ..
