#! /bin/bash

[ -v cc ] || cc=gcc
[ -v cxx ] || cxx=g++

#fetch submodules
git submodule init

#build machete
cd machete
mkdir -p lib obj bin
make 
cp lib/* ../lib/
cp mach ../bin/
cd .. 

#build SZ
cd SZ
git checkout v2.1.12
mkdir -p build
cd build
cmake ..
cmake --build .
cp sz/libSZ.so ../../lib/
cd ../..
$cxx other/test_sz.cpp -o bin/sztest -Llib -lSZ 

#build Gorilla
cd gorilla
go build 
cp gorilla ../bin/gorilla 
cd ..
