#! /bin/bash 

[ -v cc ] || cc=gcc

#fetch submodules
git submodule init

build influxdb
cd influxdb
for ver in void ori sz mach 
do 
        git checkout $ver 
        make 
        cp bin/linux/influxd ../bin/influxd-$ver 

        git checkout $ver-nc 
        make 
        cp bin/linux/influxd ../bin/influxd-$ver-nc
done 

# build sz server
$cc -O3 other/server.c -o bin/szserver 
$cc -O3 other/enco_server.c -o bin/enco_server -Llib -lSZ
$cc -O3 other/deco_server.c -o bin/deco_server -Llib -lSZ